PI-Defender: K_WHITELIST Class Reference
K_WHITELIST Class Reference
#include <K_Whitelist.hpp>
Classes
struct _WHITELIST
Static Public Member Functions
static VOID Unload ()
Free previously allocated memory.
static NTSTATUS Initialize (_In_ PKEY_VALUE_PARTIAL_INFORMATION pInfo)
Set maximum size of Cache and initialize mutex.
static NTSTATUS IsInWhitelist (_In_ PUNICODE_STRING szTestString, _Out_ BOOLEAN *bResult)
Check if whitelist contains provided string.
Private Types
typedef struct K_WHITELIST::_WHITELIST WHITELIST
typedef struct K_WHITELIST::_WHITELIST * PWHITELIST
Static Private Attributes
static WHITELIST _Whitelist = { nullptr, 0 }
Member Typedef Documentation
PWHITELIST
typedef struct K_WHITELIST::_WHITELIST * K_WHITELIST::PWHITELIST private
WHITELIST
typedef struct K_WHITELIST::_WHITELIST K_WHITELIST::WHITELIST private
Member Function Documentation
Initialize()
NTSTATUS K_WHITELIST::Initialize (_In_ PKEY_VALUE_PARTIAL_INFORMATION pInfo) static
Set maximum size of Cache and initialize mutex.
Parameters
[in] pInfo - Pointer to a structure containing data extracted from the registy relative to the whitelist.
Returns
STATUS_SUCCESS - No error occurs.
Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by K_CONFIGURATION::Initialize().
IsInWhitelist()
NTSTATUS K_WHITELIST::IsInWhitelist (_In_ PUNICODE_STRING szTestString, _Out_ BOOLEAN * bResult) static
Check if whitelist contains provided string.
Parameters
[in] szTestString - String to test (UNICODE_STRING)
[in] bResult - Pointer that receive result (out)
Returns
status - NTSTATUS Error code.
Referenced by K_CONFIGURATION::IsInWhitelist().
Unload()
VOID K_WHITELIST::Unload () static
Free previously allocated memory.
Called by DriverUnload.
Parameters
None.
Returns
None.
Referenced by K_CONFIGURATION::Unload().
Member Data Documentation
_Whitelist
K_WHITELIST::WHITELIST K_WHITELIST::_Whitelist = { nullptr, 0 } static private
Referenced by Initialize(), IsInWhitelist(), and Unload().
The documentation for this class was generated from the following files:
K_Whitelist.hpp
K_Whitelist.cpp