PI-Defender: K_COMMUNICATION Class Reference
K_COMMUNICATION Class Reference
#include <K_Communication.hpp>
Public Member Functions
VOID Unload ()
Unload the communication.
NTSTATUS Initialize (_In_ PCWSTR szPort, _In_ LONG lMaxClients)
Initialize the communicaton.
NTSTATUS Send (_In_ PDATA_TRANSMIT pData, _Out_ DATA_REPLY *pReply)
This function is used to send Data to the User-Mode service.
Static Private Member Functions
static NTSTATUS _NewConnectionCallback (_In_ PFLT_PORT pClientPort, _In_ PVOID pServerPortCookie, _In_ PVOID pConnectionContext, _In_ ULONG ulSizeOfContext, _Out_ PVOID *pConnectionPortCookie)
The connection notify callback is called when a user mode application connect to the server port.
static VOID _DisconnectionCallback (_In_ PVOID pConnectionCookie)
The disconnection notify callback is called when a user mode application disconnect from the server port.
Private Attributes
PFLT_PORT _pServerPort
Member Function Documentation
_DisconnectionCallback()
VOID K_COMMUNICATION::_DisconnectionCallback (_In_ PVOID pConnectionCookie) static private
The disconnection notify callback is called when a user mode application disconnect from the server port.
Parameters
[in] pConnectionCookie - Pointer to information that uniquely identifies this client port.
Returns
STATUS_SUCCESS - No error occurs.
Other statuS - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by Initialize().
_NewConnectionCallback()
NTSTATUS K_COMMUNICATION::_NewConnectionCallback (_In_ PFLT_PORT pClientPort, _In_ PVOID pServerPortCookie, _In_ PVOID pConnectionContext, _In_ ULONG ulSizeOfContext, _Out_ PVOID * pConnectionPortCookie) static private
The connection notify callback is called when a user mode application connect to the server port.
Parameters
[in] pClientPort - Client port that is established between the user-mode application and the kernel-mode minifilter driver.
[in] pServerPortCookie - Pointer to context information defined by the minifilter driver (can be used to distinguish multiple communication port from same driver).
[in] pConnectionContext - Context information pointer that the user-mode application passed in the lpContext parameter.
[in] ulSizeOfContext - Size of the context
[out] pConnectionPortCookie - Pointer to information that uniquely identifies this client port.
Returns
STATUS_SUCCESS - No error occurs.
Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by Initialize().
Initialize()
NTSTATUS K_COMMUNICATION::Initialize (_In_ PCWSTR szPort, _In_ LONG lMaxClients)
Initialize the communicaton.
Parameters
[in] szPort - Port communication handle.
[in] lMaxClients - Number of clients allowed to connect simultanely to the service.
Returns
STATUS_SUCCESS - No error occurs.
Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by K_FILTER::Initialize().
Send()
NTSTATUS K_COMMUNICATION::Send (_In_ PDATA_TRANSMIT pData, _Out_ DATA_REPLY * pReply)
This function is used to send Data to the User-Mode service.
Parameters
[in] pData - Structure to be transmited to the user-mode service
[out] pReply - Structure used by the user-mode service to reply
Returns
STATUS_SUCCESS - No error occurs.
Other statuS - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by K_OB::_PreObCallback().
Unload()
VOID K_COMMUNICATION::Unload ()
Unload the communication.
It is called by Filter::Unload/.
Parameters
None.
Returns
None.
Referenced by K_FILTER::Unload().
Member Data Documentation
_pServerPort
PFLT_PORT K_COMMUNICATION::_pServerPort private
Referenced by Unload().
The documentation for this class was generated from the following files:
K_Communication.hpp
K_Communication.cpp