PI-Defender: K_OB Class Reference
K_OB Class Reference
#include <K_ObCallback.hpp>
Public Member Functions
NTSTATUS Initialize ()
Register the ObCallback routine.
Static Public Member Functions
static VOID Unload ()
Routine used to unload ObCallback.
Static Private Member Functions
static BOOLEAN _Checks (_In_ PVOID pPreOperationInfo)
@brieF Checks if :
static OB_PREOP_CALLBACK_STATUS _PreObCallback (_In_ PVOID pRegistrationContext, _In_ POB_PRE_OPERATION_INFORMATION pPreInfo)
We get notify when a process want a handle.
Member Function Documentation
_Checks()
BOOLEAN K_OB::_Checks (_In_ PVOID pOperationInfo) static private
@brieF Checks if :
A client is connected
The IRQL is at PASSIVE_LEVEL
We are dealing with kernel handle If 'bFlags' is TRUE: Pre Operation Callback If 'bFlags' is FALSE: Post Operation Callback
Parameters
[in] pOperationInfo - Pointer to a structure that will be cast depending on the bFlags value (see description above)
Returns
TRUE - Pass the checks FALSE - Blocked
Referenced by _PreObCallback().
_PreObCallback()
OB_PREOP_CALLBACK_STATUS K_OB::_PreObCallback (_In_ PVOID pRegistrationContext, _In_ POB_PRE_OPERATION_INFORMATION pPreOperationInfo) static private
We get notify when a process want a handle.
We communicate with the user-mode service to know if this process is signed.
If the process is signed, we don't filter.
Else, we filter it and remove 'PROCESS_VM_WRITE' and 'PROCESS_VM_OPERATION' to the desired access.
Parameters
[in] pRegistrationContext - Context that the driver want to pass to this callback.
[in] pPreOperationInfo - Pointer to OB_PRE_OPERATION_INFORMATION structure, that receive information about the handle created.
Returns
OB_PREOP_SUCCESS - Pre Operation callback finished.
Referenced by Initialize().
Initialize()
NTSTATUS K_OB::Initialize ()
Register the ObCallback routine.
/!\ In order to register the callback you must have:
a signed driver
/integritycheck parameter added in the linker Else, you'll get '0xC0000022' error
Parameters
None.
Returns
STATUS_SUCCESS - No error occurs. Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by DriverEntry().
Unload()
VOID K_OB::Unload () static
Routine used to unload ObCallback.
Parameters
None.
Returns
None.
Referenced by DriverUnload().
The documentation for this class was generated from the following files:
K_ObCallback.hpp
K_ObCallback.cpp