PI-Defender: U_COMMUNICATION Class Reference
U_COMMUNICATION Class Reference
#include <U_Communication.hpp>
Classes
struct _MESSAGE
struct _REPLY_MESSAGE
struct _THREAD_PARAMETERS
Public Types
typedef struct U_COMMUNICATION::_MESSAGE MESSAGE
typedef struct U_COMMUNICATION::_MESSAGE * PMESSAGE
typedef struct U_COMMUNICATION::_THREAD_PARAMETERS THREAD_PARAMETERS
typedef struct U_COMMUNICATION::_THREAD_PARAMETERS * PTHREAD_PARAMETERS
Public Member Functions
U_COMMUNICATION ()
_Success_ (return==S_OK) HRESULT Connect(_In_ PWSTR szPortName
VOID Disconnect ()
Disconnect the client.
Static Public Member Functions
static VOID ListenerThread (_In_ LPVOID lpParam)
Thread listening message sends from kernel driver.
Public Attributes
_In_ DWORD dwListeningThreads
_In_ DWORD _Out_ HANDLE * hCompletion
_In_ DWORD _Out_ HANDLE _Out_ HANDLE * hPort
Private Types
typedef struct U_COMMUNICATION::_REPLY_MESSAGE REPLY_MESSAGE
typedef struct U_COMMUNICATION::_REPLY_MESSAGE * PREPLY_MESSAGE
Static Private Member Functions
static VOID CALLBACK _WorkerThread (_Inout_ PTP_CALLBACK_INSTANCE Instance, _Inout_opt_ PVOID Context, _Inout_ PTP_WORK Work)
Worker thread used to check file signature.
static _Success_ (return) VOID _CreateThreadPool(_In_ DWORD dwMinWorkerThreads
static VOID _Reply (_In_ HANDLE hPort, _In_ PMESSAGE pMsg, _In_ DATA_REPLY DataToReply)
Reply to the kernel driver.
static VOID _PumpMessageInQueue (_In_ HANDLE hPort, _In_ PMESSAGE pMsg)
Push a new message in the queue.
Private Attributes
HANDLE _hPort
HANDLE _hCompletion
static _In_ DWORD dwMaxWorkerThreads
static _In_ DWORD _Out_ TP_CALLBACK_ENVIRON * pEnv
Member Typedef Documentation
MESSAGE
typedef struct U_COMMUNICATION::_MESSAGE U_COMMUNICATION::MESSAGE
PMESSAGE
typedef struct U_COMMUNICATION::_MESSAGE * U_COMMUNICATION::PMESSAGE
PREPLY_MESSAGE
typedef struct U_COMMUNICATION::_REPLY_MESSAGE * U_COMMUNICATION::PREPLY_MESSAGE private
PTHREAD_PARAMETERS
typedef struct U_COMMUNICATION::_THREAD_PARAMETERS * U_COMMUNICATION::PTHREAD_PARAMETERS
REPLY_MESSAGE
typedef struct U_COMMUNICATION::_REPLY_MESSAGE U_COMMUNICATION::REPLY_MESSAGE private
THREAD_PARAMETERS
typedef struct U_COMMUNICATION::_THREAD_PARAMETERS U_COMMUNICATION::THREAD_PARAMETERS
Constructor & Destructor Documentation
U_COMMUNICATION()
U_COMMUNICATION::U_COMMUNICATION () inline
Member Function Documentation
_PumpMessageInQueue()
VOID U_COMMUNICATION::_PumpMessageInQueue (_In_ HANDLE hPort, _In_ PMESSAGE pMsg) static private
Push a new message in the queue.
Parameters
[in] hPort - Communication handle port.
[in] pMsg - Structure that defines the data transmitted from kernel <-> user-mode .
Returns
None.
Referenced by _WorkerThread().
_Reply()
VOID U_COMMUNICATION::_Reply (_In_ HANDLE hPort, _In_ PMESSAGE pMsg, _In_ DATA_REPLY DataToReply) static private
Reply to the kernel driver.
Parameters
[in] hPort - Communication handle port.
[in] pMsg - Structure that will receive the message from the kernel.
[in] DataToReply - Structure used to hold the data that will be send to the kernel.
Returns
None.
Referenced by _WorkerThread().
_Success_() [1/2]
static U_COMMUNICATION::_Success_ (return) static private
_Success_() [2/2]
U_COMMUNICATION::_Success_ (return = = S_OK)
_WorkerThread()
VOID CALLBACK U_COMMUNICATION::_WorkerThread (_Inout_ PTP_CALLBACK_INSTANCE Instance, _Inout_opt_ PVOID Context, _Inout_ PTP_WORK Work) static private
Worker thread used to check file signature.
Parameters
[in,out] Instance - Structure that defines the callback instance.
[in,out] Context - Parameter passed to the thread
[in,out] Work - Structure that defines the Work object generated by the callback.
Returns
None.
Referenced by ListenerThread().
Disconnect()
VOID U_COMMUNICATION::Disconnect ()
Disconnect the client.
Parameters
None.
Returns
None.
Referenced by U_CONTROLLER::SvcCtrlHandler().
ListenerThread()
VOID U_COMMUNICATION::ListenerThread (_In_ LPVOID lpParam) static
Thread listening message sends from kernel driver.
Parameters
[in] lpParam - Thread parameters pass to the function (Completion & Client Port).
Returns
None.
Referenced by SvcMain().
Member Data Documentation
_hCompletion
HANDLE U_COMMUNICATION::_hCompletion private
Referenced by Disconnect(), and U_COMMUNICATION().
_hPort
HANDLE U_COMMUNICATION::_hPort private
Referenced by Disconnect(), and U_COMMUNICATION().
dwListeningThreads
_In_ DWORD U_COMMUNICATION::dwListeningThreads
Referenced by _Success_().
dwMaxWorkerThreads
_In_ DWORD U_COMMUNICATION::dwMaxWorkerThreads private
hCompletion
_In_ DWORD _Out_ HANDLE* U_COMMUNICATION::hCompletion
Referenced by _Success_().
hPort
_In_ DWORD _Out_ HANDLE _Out_ HANDLE* U_COMMUNICATION::hPort
Referenced by _PumpMessageInQueue(), _Reply(), and _Success_().
pEnv
_In_ DWORD _Out_ TP_CALLBACK_ENVIRON* U_COMMUNICATION::pEnv private
The documentation for this class was generated from the following files:
U_Communication.hpp
U_Communication.cpp