PI-Defender: U_LOGS Class Reference
U_LOGS Class Reference
#include <U_Logs.hpp>
Static Public Member Functions
static BOOLEAN Initialize (_In_ PCWSTR szSourceName)
Initialize the service eventlog.
static BOOLEAN Unload ()
Close the service eventlog.
static VOID SvcReportEvent (_In_ PCWSTR szFunction, _In_ INT iEventType, _In_ DWORD dwEventId, _In_ PCWSTR szComment)
Send the reported event in the Event Viewer (Application -> PI-Defender_UM).
Static Private Attributes
static HANDLE _hEventLog = NULL
Member Function Documentation
Initialize()
BOOLEAN U_LOGS::Initialize (_In_ PCWSTR szSourceName) static
Initialize the service eventlog.
Parameters
[in] szSourceName - Name of the source event (service name)
Returns
TRUE - No error occurs. FALSE - Error occurs
Referenced by _tmain().
SvcReportEvent()
VOID U_LOGS::SvcReportEvent (_In_ PCWSTR szFunction, _In_ INT iEventType, _In_ DWORD dwEventId, _In_ PCWSTR szComment) static
Send the reported event in the Event Viewer (Application -> PI-Defender_UM).
Parameters
[in] szFunction - Function causing the error
[in] iEventType - Type of event (EVENTLOG_ERROR_TYPE, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, EVENTLOG_INFORMATION_TYPE, EVENTLOG_WARNING_TYPE)
[in] szComment - Comment to be added to the log.
Returns
None.
Referenced by U_CONFIGURATION::_CreateRegistryForLogs(), U_COMMUNICATION::_Reply(), _Success_(), U_COMMUNICATION::_WorkerThread(), U_CONFIGURATION::DeleteLogsRegistry(), Install(), U_COMMUNICATION::ListenerThread(), Service(), U_CONTROLLER::SvcCtrlHandler(), and SvcMain().
Unload()
BOOLEAN U_LOGS::Unload () static
Close the service eventlog.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Member Data Documentation
_hEventLog
HANDLE U_LOGS::_hEventLog = NULL static private
Referenced by Initialize(), SvcReportEvent(), and Unload().
The documentation for this class was generated from the following files:
U_Logs.hpp
U_Logs.cpp