PI-Defender: K_FILTER Class Reference
K_FILTER Class Reference
#include <K_Filter.hpp>
Public Member Functions
NTSTATUS Initialize (_In_ PDRIVER_OBJECT pDriverObject)
Initialize the filter.
Static Public Member Functions
static NTSTATUS Unload (_In_ FLT_FILTER_UNLOAD_FLAGS Flags)
Unload the communication & the filter.
Member Function Documentation
Initialize()
NTSTATUS K_FILTER::Initialize (_In_ PDRIVER_OBJECT pDriverObject)
Initialize the filter.
Parameters
[in] pDriverObject - Pointer to DRIVER_OBJECT structure
Returns
STATUS_SUCCESS - No error occurs. Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by DriverEntry().
Unload()
NTSTATUS K_FILTER::Unload (_In_ FLT_FILTER_UNLOAD_FLAGS Flags) static
Unload the communication & the filter.
Parameters
[in] Flags - Not used
Returns
STATUS_SUCCESS - No error occurs. Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by DriverEntry(), and Initialize().
The documentation for this class was generated from the following files:
K_Filter.hpp
K_Filter.cpp