PI-Defender: U_CONFIGURATION Class Reference
U_CONFIGURATION Class Reference
#include <U_Configuration.hpp>
Static Public Member Functions
static LSTATUS SetServiceConfiguration ()
Create registry keys needed for the service configuration.
static LSTATUS SetDriverConfiguration ()
Create registry keys needed for the driver configuration.
static VOID PrintConfiguration ()
Print and populate service structure with the configuration read from registry keys.
static LSTATUS DeleteLogsRegistry ()
Delete all the registry keys needed for ETW Logs.
static DWORD GetListenerThreads ()
Get the number of threads of the service by reading the values in the Registry.
static DWORD GetMinWorkerThreads ()
Get the number of threads of the service by reading the values in the Registry.
static DWORD GetMaxWorkerThreads ()
Get the number of threads of the service by reading the values in the REGISTRY::
static DWORD GetMaxClients ()
Get the maximum number of clients of the service by reading the values in the REGISTRY::
[i] This value is loaded but never used by the service (only for printing purpose).
static PCWSTR GetCommunicationPort ()
Get the communication port used by the driver to interact with the service.
static PWHITELIST GetWhitelist ()
Get the whitelist used to allow user-specified apps.
static DWORD GetCacheSize ()
Get the number of items to be kept in the cache by the filter.
Static Private Member Functions
static LSTATUS _CreateRegistryForLogs ()
Create all the registry keys needed for ETW Logs.
Member Function Documentation
_CreateRegistryForLogs()
LSTATUS U_CONFIGURATION::_CreateRegistryForLogs () static private
Create all the registry keys needed for ETW Logs.
Parameters
None.
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by SetServiceConfiguration().
DeleteLogsRegistry()
LSTATUS U_CONFIGURATION::DeleteLogsRegistry () static
Delete all the registry keys needed for ETW Logs.
This function is called when the service UM is deleted.
Parameters
None.
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by Delete().
GetCacheSize()
DWORD U_CONFIGURATION::GetCacheSize () static
Get the number of items to be kept in the cache by the filter.
Parameters
None.
Returns
dwCacheSize - number of items to be kept in the cache by the filter.
Referenced by PrintConfiguration().
GetCommunicationPort()
PCWSTR U_CONFIGURATION::GetCommunicationPort () static
Get the communication port used by the driver to interact with the service.
Parameters
None.
Returns
szCommunicationPort - String containing the port used by the driver to initiate the communication.
Referenced by PrintConfiguration(), and SvcMain().
GetListenerThreads()
DWORD U_CONFIGURATION::GetListenerThreads () static
Get the number of threads of the service by reading the values in the Registry.
Parameters
None.
Returns
dwThreads - Number of threads of the service.
Referenced by PrintConfiguration(), and SvcMain().
GetMaxClients()
DWORD U_CONFIGURATION::GetMaxClients () static
Get the maximum number of clients of the service by reading the values in the REGISTRY::
[i] This value is loaded but never used by the service (only for printing purpose).
The driver will also load the key to setup the communication.
Parameters
None.
Returns
dwMaxClients - Maximum number of clients allowed to connect to the driver.
Referenced by PrintConfiguration().
GetMaxWorkerThreads()
DWORD U_CONFIGURATION::GetMaxWorkerThreads () static
Get the number of threads of the service by reading the values in the REGISTRY::
Parameters
None.
Returns
dwMaxThreads - Number of threads of the service.
Referenced by PrintConfiguration(), and SvcMain().
GetMinWorkerThreads()
DWORD U_CONFIGURATION::GetMinWorkerThreads () static
Get the number of threads of the service by reading the values in the Registry.
Parameters
None.
Returns
dwMinThreads - Number of threads of the service.
Referenced by PrintConfiguration(), and SvcMain().
GetWhitelist()
PWHITELIST U_CONFIGURATION::GetWhitelist () static
Get the whitelist used to allow user-specified apps.
Parameters
None.
Returns
pWhitelist - pointer to the loaded Whitelist (Don't forget to free at unload)
Referenced by PrintConfiguration().
PrintConfiguration()
VOID U_CONFIGURATION::PrintConfiguration () static
Print and populate service structure with the configuration read from registry keys.
Max number of clients
Communication Port
Whitelist
Number of threads of the service
Parameters
None.
Returns
None.
Referenced by Query(), and Start().
SetDriverConfiguration()
LSTATUS U_CONFIGURATION::SetDriverConfiguration () static
Create registry keys needed for the driver configuration.
Parameters
None.
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by Install().
SetServiceConfiguration()
LSTATUS U_CONFIGURATION::SetServiceConfiguration () static
Create registry keys needed for the service configuration.
Parameters
None.
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by Install().
The documentation for this class was generated from the following files:
U_Configuration.hpp
U_Configuration.cpp