PI-Defender: U_CONTROLLER Class Reference
U_CONTROLLER Class Reference
#include <U_Controller.hpp>
Static Public Member Functions
static BOOLEAN InstallService (_In_ PCWSTR szServiceName, _In_ BOOLEAN bDriver)
Install the service "szServiceName".
static BOOLEAN IsServiceInstalled (_In_ PCWSTR szServiceName)
Check if the service is already installed.
static DWORD GetServiceState (_In_ PCWSTR szServiceName)
Query the service "szServiceName" and return its state.
static BOOLEAN LaunchService (_In_ PCWSTR szServiceName)
Start the service "szServiceName".
static BOOLEAN StopService (_In_ PCWSTR szServiceName)
Stop the service "szServiceName".
static BOOLEAN QueryService (_In_ PCWSTR szServiceName)
Query the service "szServiceName" configuration.
static BOOLEAN DelService (_In_ PCWSTR szServiceName)
Delete the service "szServiceName".
static VOID WINAPI SvcCtrlHandler (_In_ DWORD dwCtrl)
Receive signal send by the User / SC Manager, handle it, update service status.
static VOID SvcReportStatus (_In_ SERVICE_STATUS SvcStatus, _In_ SERVICE_STATUS_HANDLE SvcStatusHandle, _In_ DWORD dwCurrentState, _In_ DWORD dwWin32ExitCode, _In_ DWORD dwWaitHint)
Depending on the state of the service, it can receive order from the user space.
Static Private Member Functions
static SC_HANDLE _GetSCMHandle ()
Get a handle to the Service Controller Database.
static SC_HANDLE _GetServiceHandle (_In_ SC_HANDLE hSCManager, _In_ PCWSTR szServiceName)
Get a handle to the service.
Member Function Documentation
_GetSCMHandle()
SC_HANDLE U_CONTROLLER::_GetSCMHandle () static private
Get a handle to the Service Controller Database.
Parameters
None
Returns
SC_HANDLE (no error occurs) NULL (error occurs)
Referenced by GetServiceState(), InstallService(), IsServiceInstalled(), LaunchService(), QueryService(), and StopService().
_GetServiceHandle()
SC_HANDLE U_CONTROLLER::_GetServiceHandle (_In_ SC_HANDLE hSCManager, _In_ PCWSTR szServiceName) static private
Get a handle to the service.
Parameters
[in] hSCManager - Handle to the service Manager
[in] szServiceName - Name of the service
Returns
SC_HANDLE (no error occurs)
NULL (error occurs)
Referenced by LaunchService().
DelService()
BOOLEAN U_CONTROLLER::DelService (_In_ PCWSTR szServiceName) static
Delete the service "szServiceName".
Parameters
[in] szServiceName - Name of the service
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by Delete().
GetServiceState()
DWORD U_CONTROLLER::GetServiceState (_In_ PCWSTR szServiceName) static
Query the service "szServiceName" and return its state.
Parameters
[in] szServiceName - Name of the service
Returns
dwStatus - current state of the service, can be one of the following values: SERVICE_CONTINUE_PENDIND, SERVICE_PAUSE_PENDING, SERVICE_PAUSED, SERVICE_RUNNING, SERVICE_START_PENDING, SERVICE_STOP_PENDING, SERVICE_STOPPED
Referenced by StopService().
InstallService()
BOOLEAN U_CONTROLLER::InstallService (_In_ PCWSTR szServiceName, _In_ BOOLEAN bDriver) static
Install the service "szServiceName".
Parameters
[in] szServiceName - Name of the service.
Returns
TRUE (no error occurs) FALSE (error occurs)
Referenced by Install().
IsServiceInstalled()
BOOLEAN U_CONTROLLER::IsServiceInstalled (_In_ PCWSTR szServiceName) static
Check if the service is already installed.
Parameters
[in] szServiceName - Name of the service
Returns
TRUE (no error occurs) - FALSE (error occurs)
Referenced by Install(), and Query().
LaunchService()
BOOLEAN U_CONTROLLER::LaunchService (_In_ PCWSTR szServiceName) static
Start the service "szServiceName".
Parameters
[in] szServiceName - Name of the service
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by Start(), and SvcMain().
QueryService()
BOOLEAN U_CONTROLLER::QueryService (_In_ PCWSTR szServiceName) static
Query the service "szServiceName" configuration.
Parameters
[in] szServiceName - Name of the service
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by Query().
StopService()
BOOLEAN U_CONTROLLER::StopService (_In_ PCWSTR szServiceName) static
Stop the service "szServiceName".
Parameters
[in] szServiceName - Name of the service
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by Stop(), and SvcCtrlHandler().
SvcCtrlHandler()
VOID WINAPI U_CONTROLLER::SvcCtrlHandler (_In_ DWORD dwCtrl) static
Receive signal send by the User / SC Manager, handle it, update service status.
Parameters
[in] dwCtrl - Service signal.
Returns
None.
Referenced by SvcMain().
SvcReportStatus()
VOID U_CONTROLLER::SvcReportStatus (_In_ SERVICE_STATUS SvcStatus, _In_ SERVICE_STATUS_HANDLE SvcStatusHandle, _In_ DWORD dwCurrentState, _In_ DWORD dwWin32ExitCode, _In_ DWORD dwWaitHint) static
Depending on the state of the service, it can receive order from the user space.
Parameters
[in] dwCurrentState - State of the service.
[in] dwWin32ExitCode - Exit code.
[in] dwCurrentState - State of the service.
[in] dwWaitHint - Max Waiting time before action occur.
Returns
None.
Referenced by SvcCtrlHandler(), and SvcMain().
The documentation for this class was generated from the following files:
U_Controller.hpp
U_Controller.cpp