PI-Defender: U_Service.cpp File Reference
U_Service.cpp File Reference
Entrypoint of the process & the service.
#include "U_Service.hpp"
Functions
BOOLEAN Install ()
Wrap the installation of the service.
BOOLEAN Query ()
Wrap the query information about the service.
BOOLEAN Delete ()
Wrap the deletion of the driver and the service.
BOOLEAN Start ()
Wrap the start of the service.
BOOLEAN Stop ()
Wrap the stop of the driver and the service.
VOID Service ()
Wrap the call to the service entrypoint.
int _tmain (_In_ int argc, _In_ TCHAR *argv[])
Entrypoint of the user space executable.
VOID WINAPI SvcMain (_In_ DWORD dwArgc, _In_ PWSTR *pszArgv)
Entrypoint and core of the user space service.
Variables
U_COMMUNICATION Communication
sSERVICE strctService = { 0 }
Detailed Description
Entrypoint of the process & the service.
Author
NAVAL-Group (Berenger BRAULT, Nicolas JALLET)
Version
1.0
Date
02/06/2022
Copyright
©Naval Group SA. This document in its content and form is the property of Naval Group SA and/or third parties. This project is released under the LGPLv3 license.
Function Documentation
_tmain()
int _tmain (_In_ int argc, _In_ TCHAR * argv[])
Entrypoint of the user space executable.
Parameters
[in] argc - Number of arguments.
[in] argv - Array that contains arguments values.
Returns
EXIT_SUCCESS (0) - No error occurs. EXIT_FAILURE (1) - Error occurs.
Delete()
BOOLEAN Delete ()
Wrap the deletion of the driver and the service.
[i] If an error occur when trying to delete the driver, the service will not be deleted.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Install()
BOOLEAN Install ()
Wrap the installation of the service.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Query()
BOOLEAN Query ()
Wrap the query information about the service.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Service()
VOID Service ()
Wrap the call to the service entrypoint.
Parameters
None.
Returns
None.
Referenced by _tmain().
Start()
BOOLEAN Start ()
Wrap the start of the service.
Parameters
one.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Stop()
BOOLEAN Stop ()
Wrap the stop of the driver and the service.
[i] If the driver failed to stop, the service isn't stopped.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
SvcMain()
VOID WINAPI SvcMain (_In_ DWORD dwArgc, _In_ PWSTR * pszArgv)
Entrypoint and core of the user space service.
Parameters
[in] dwArgc - Number of arguments
[out] lpszArgv - Array that contains arguments values
Returns
None.
Referenced by Service().
Variable Documentation
Communication
U_COMMUNICATION Communication
Referenced by K_FILTER::Initialize(), U_CONTROLLER::SvcCtrlHandler(), SvcMain(), and K_FILTER::Unload().
strctService
sSERVICE strctService = { 0 }
Referenced by U_CONTROLLER::SvcCtrlHandler(), and SvcMain().