PI-Defender: K_HELPER Class Reference
K_HELPER Class Reference
#include <K_Helper.hpp>
Public Types
typedef NTSTATUS(* QUERY_INFO_PROCESS) (__in HANDLE hProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID pProcessInformation, __in ULONG ulProcessInformationLength, __out_opt PULONG ulReturnLength)
Static Public Member Functions
static NTSTATUS GetFileHash (_In_ PUNICODE_STRING szFileName, _Out_ PVOID *pHash, _Out_ ULONG *ulHashSize)
static NTSTATUS ConvertNtPathToDosPath (_In_ UNICODE_STRING szFullImageName, _Out_ UNICODE_STRING *szDosPath)
static NTSTATUS MyZwOpenKey (_Out_ PHANDLE hKey, _In_ PUNICODE_STRING szKeyPath)
static NTSTATUS MyZwQueryValueKey (_In_ const HANDLE hKey, _In_ PUNICODE_STRING szValueName, _Out_ PKEY_VALUE_PARTIAL_INFORMATION *pRetAddress)
static BOOLEAN IsValidString (_In_ const _KEY_VALUE_PARTIAL_INFORMATION *pInfo)
Returns TRUE if the passed _KEY_VALUE_PARTIAL_INFORMATION structure extracted from the Registry contains a valid Unicode string (REG_SZ type), else returns FALSE.
static BOOLEAN IsValidStringArray (_In_ const _KEY_VALUE_PARTIAL_INFORMATION *pInfo)
Returns TRUE if the passed _KEY_VALUE_PARTIAL_INFORMATION structure extracted from the Registry contains a valid Unicode string array (REG_MULTI_SZ type), else returns FALSE
The REG_MULTI_SZ type is a sequence of null-terminated strings, terminated by a empty string (\0).
static ULONG CountWStringsInBuffer (_In_ PCWSTR szBuffer, _In_ const ULONG ulSize)
Returns the number of Unicode strings found in a buffer (raw data from REG_MULTI_SZ).
static NTSTATUS GetFullImageNameByHandle (_In_ HANDLE hProcessId, _Out_ UNICODE_STRING *szFullImageName)
static INT MyNtPathCchRemoveFileSpec (_In_ PUNICODE_STRING szPath)
static NTSTATUS DosPathtoNtPath (_In_ PCUNICODE_STRING szPath, _Out_ UNICODE_STRING *szNormalized)
Member Typedef Documentation
QUERY_INFO_PROCESS
typedef NTSTATUS(* K_HELPER::QUERY_INFO_PROCESS) (__in HANDLE hProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID pProcessInformation, __in ULONG ulProcessInformationLength, __out_opt PULONG ulReturnLength)
Member Function Documentation
ConvertNtPathToDosPath()
static NTSTATUS K_HELPER::ConvertNtPathToDosPath (_In_ UNICODE_STRING szFullImageName, _Out_ UNICODE_STRING * szDosPath) static
Referenced by K_OB::_PreObCallback().
CountWStringsInBuffer()
ULONG K_HELPER::CountWStringsInBuffer (_In_ PCWSTR szBuffer, _In_ const ULONG ulSize) static
Returns the number of Unicode strings found in a buffer (raw data from REG_MULTI_SZ).
Parameters
[in] szBuffer - Pointer to a buffer that contains raw data from a REG_MULTI_SZ
[in] ulSize - Buffer size in bytes
Returns
count - Number of Unicode strings found in Buffer.
Referenced by K_WHITELIST::Initialize().
DosPathtoNtPath()
static NTSTATUS K_HELPER::DosPathtoNtPath (_In_ PCUNICODE_STRING szPath, _Out_ UNICODE_STRING * szNormalized) static
Referenced by K_WHITELIST::Initialize().
GetFileHash()
static NTSTATUS K_HELPER::GetFileHash (_In_ PUNICODE_STRING szFileName, _Out_ PVOID * pHash, _Out_ ULONG * ulHashSize) static
Referenced by K_OB::_PreObCallback().
GetFullImageNameByHandle()
static NTSTATUS K_HELPER::GetFullImageNameByHandle (_In_ HANDLE hProcessId, _Out_ UNICODE_STRING * szFullImageName) static
Referenced by K_OB::_PreObCallback().
IsValidString()
BOOLEAN K_HELPER::IsValidString (_In_ const _KEY_VALUE_PARTIAL_INFORMATION * pInfo) static
Returns TRUE if the passed _KEY_VALUE_PARTIAL_INFORMATION structure extracted from the Registry contains a valid Unicode string (REG_SZ type), else returns FALSE.
Parameters
[in] pInfo - Pointer to a _KEY_VALUE_PARTIAL_INFORMATION that contains data extracted from a value in the Registry
Returns
TRUE - The provided structure contains a valid Unicode string (REG_SZ). FALSE - The provided structure does not contain a valid Unicode string (REG_SZ).
Referenced by K_CONFIGURATION::Initialize().
IsValidStringArray()
BOOLEAN K_HELPER::IsValidStringArray (_In_ const _KEY_VALUE_PARTIAL_INFORMATION * pInfo) static
Returns TRUE if the passed _KEY_VALUE_PARTIAL_INFORMATION structure extracted from the Registry contains a valid Unicode string array (REG_MULTI_SZ type), else returns FALSE
The REG_MULTI_SZ type is a sequence of null-terminated strings, terminated by a empty string (\0).
ex: String1\0String2\0String3\0LastString\0\0
Parameters
[in] pInfo - pointer to a _KEY_VALUE_PARTIAL_INFORMATION that contains data extracted from a value in the Registry
Returns
TRUE - The provided structure contains a valid Unicode string array (REG_MULTI_SZ). FALSE - The provided structure does not contain a valid Unicode string array (REG_MULTI_SZ).
Referenced by K_CONFIGURATION::Initialize().
MyNtPathCchRemoveFileSpec()
static INT K_HELPER::MyNtPathCchRemoveFileSpec (_In_ PUNICODE_STRING szPath) static
Referenced by K_WHITELIST::IsInWhitelist().
MyZwOpenKey()
static NTSTATUS K_HELPER::MyZwOpenKey (_Out_ PHANDLE hKey, _In_ PUNICODE_STRING szKeyPath) static
Referenced by K_CONFIGURATION::Initialize().
MyZwQueryValueKey()
static NTSTATUS K_HELPER::MyZwQueryValueKey (_In_ const HANDLE hKey, _In_ PUNICODE_STRING szValueName, _Out_ PKEY_VALUE_PARTIAL_INFORMATION * pRetAddress) static
Referenced by K_CONFIGURATION::Initialize().
The documentation for this class was generated from the following files:
K_Helper.hpp
K_Helper.cpp