PI-Defender: K_CACHE Class Reference
K_CACHE Class Reference
#include <K_Cache.hpp>
Classes
struct _CACHELIST
struct _HASH
Static Public Member Functions
static VOID Initialize (_In_ DWORD dwSize)
Set maximum size of Cache and initialize mutex.
static BOOLEAN GetCachedValue (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN *bIsOk)
Set bIsOk to TRUE if cache contains specified Hash, FALSE otherwise.
static VOID Add (_In_ ULONG ulHashSize, _In_ PVOID pHash, _In_ BOOLEAN bIsOk)
Add a Hash in the Cache and remember if it is signed or not.
Private Types
typedef struct K_CACHE::_HASH HASH
typedef struct K_CACHE::_HASH * PHASH
typedef struct K_CACHE::_CACHELIST CACHELIST
typedef struct K_CACHE::_CACHELIST * PCACHELIST
Static Private Member Functions
static BOOLEAN _GetCachedValue (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN *bIsOk)
Set "pbIsOk" to TRUE if cache contains specified Hash, FALSE otherwise.
Static Private Attributes
static CACHELIST _Cache = { 0, 0, nullptr }
static PKGUARDED_MUTEX _pMutex = nullptr
Member Typedef Documentation
CACHELIST
typedef struct K_CACHE::_CACHELIST K_CACHE::CACHELIST private
HASH
typedef struct K_CACHE::_HASH K_CACHE::HASH private
PCACHELIST
typedef struct K_CACHE::_CACHELIST * K_CACHE::PCACHELIST private
PHASH
typedef struct K_CACHE::_HASH * K_CACHE::PHASH private
Member Function Documentation
_GetCachedValue()
BOOLEAN K_CACHE::_GetCachedValue (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN * bIsOk) static private
Set "pbIsOk" to TRUE if cache contains specified Hash, FALSE otherwise.
/!\ WARNING, not protected with mutex, use GetCachedValue() for public access instead
Parameters
[in] "ulHashSize"- Size of bHash in bytes
[in] pHash - Pointer to buffer that holds Hash
[outopt] "bIsOk" - Pointer to a BOOLEAN variable that will get cache result (optional)
Returns
TRUE - No error occurs.
FALSE - Error occurs
Referenced by Add(), and GetCachedValue().
Add()
VOID K_CACHE::Add (_In_ ULONG ulHashSize, _In_ PVOID pHash, _In_ BOOLEAN bIsOk) static
Add a Hash in the Cache and remember if it is signed or not.
Parameters
[in] "ulHashSize"- Size of bHash in bytes
[in] pHash - Pointer to buffer that holds Hash
[outopt] "bIsOk" - Pointer to a BOOLEAN variable that will get cache result (optional)
Returns
None.
Referenced by K_CONFIGURATION::AddToCache().
GetCachedValue()
BOOLEAN K_CACHE::GetCachedValue (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN * bIsOk) static
Set bIsOk to TRUE if cache contains specified Hash, FALSE otherwise.
Wrapper for _GetCachedValue() with mutex protection (public use).
Parameters
[in] "ulHashSize"- Size of bHash in bytes
[in] pHash - Pointer to buffer that holds Hash
[outopt] "bIsOk" - Pointer to a BOOLEAN variable that will get cache result (optional)
Returns
TRUE - No error occurs.
FALSE - Error occurs
Referenced by K_CONFIGURATION::IsInCache().
Initialize()
VOID K_CACHE::Initialize (_In_ DWORD dwSize) static
Set maximum size of Cache and initialize mutex.
Parameters
[in] dwSize - Size of the buffer (cache), number of items to be kept.
Returns
None.
Referenced by K_CONFIGURATION::Initialize().
Member Data Documentation
_Cache
K_CACHE::CACHELIST K_CACHE::_Cache = { 0, 0, nullptr } static private
Referenced by _GetCachedValue(), Add(), and Initialize().
_pMutex
PKGUARDED_MUTEX K_CACHE::_pMutex = nullptr static private
Referenced by Add(), GetCachedValue(), and Initialize().
The documentation for this class was generated from the following files:
K_Cache.hpp
K_Cache.cpp