PI-Defender: U_Service.hpp File Reference
U_Service.hpp File Reference
Header for U_Service.cpp.
#include "U_GlobalHeader.hpp"
#include "U_Configuration.hpp"
#include "U_Controller.hpp"
#include "U_Logs.hpp"
#include "U_Helper.hpp"
#include "U_Communication.hpp"
Classes
struct _sSERVICE
Macros
#define SERVICE_NAME L"PI-Defender_UM"
#define DRIVER_NAME L"PI-Defender"
#define DRIVER_SYS L"PI-Defender.sys"
#define DLL_NAME L"PI-Defender_UM_MsgFile.dll"
Typedefs
typedef struct _sSERVICE sSERVICE
Functions
BOOLEAN Install ()
Wrap the installation of the service.
BOOLEAN Query ()
Wrap the query information about the service.
BOOLEAN Delete ()
Wrap the deletion of the driver and the service.
BOOLEAN Start ()
Wrap the start of the service.
BOOLEAN Stop ()
Wrap the stop of the driver and the service.
VOID Service ()
Wrap the call to the service entrypoint.
VOID WINAPI SvcMain (_In_ DWORD dwArgc, _In_ PWSTR *pszArgv)
Entrypoint and core of the user space service.
Detailed Description
Header for U_Service.cpp.
Author
NAVAL-Group (Berenger BRAULT, Nicolas JALLET)
Version
1.0
Date
02/06/2022
Copyright
©Naval Group SA. This document in its content and form is the property of Naval Group SA and/or third parties. This project is released under the LGPLv3 license.
Macro Definition Documentation
DLL_NAME
#define DLL_NAME L"PI-Defender_UM_MsgFile.dll"
DRIVER_NAME
#define DRIVER_NAME L"PI-Defender"
DRIVER_SYS
#define DRIVER_SYS L"PI-Defender.sys"
SERVICE_NAME
#define SERVICE_NAME L"PI-Defender_UM"
Typedef Documentation
sSERVICE
typedef struct _sSERVICE sSERVICE
Function Documentation
Delete()
BOOLEAN Delete ()
Wrap the deletion of the driver and the service.
[i] If an error occur when trying to delete the driver, the service will not be deleted.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Install()
BOOLEAN Install ()
Wrap the installation of the service.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Query()
BOOLEAN Query ()
Wrap the query information about the service.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Service()
VOID Service ()
Wrap the call to the service entrypoint.
Parameters
None.
Returns
None.
Referenced by _tmain().
Start()
BOOLEAN Start ()
Wrap the start of the service.
Parameters
one.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
Stop()
BOOLEAN Stop ()
Wrap the stop of the driver and the service.
[i] If the driver failed to stop, the service isn't stopped.
Parameters
None.
Returns
TRUE - No error occurs. FALSE - Error occurs.
Referenced by _tmain().
SvcMain()
VOID WINAPI SvcMain (_In_ DWORD dwArgc, _In_ PWSTR * pszArgv)
Entrypoint and core of the user space service.
Parameters
[in] dwArgc - Number of arguments
[out] lpszArgv - Array that contains arguments values
Returns
None.
Referenced by Service().