PI-Defender: U_HELPER Class Reference
U_HELPER Class Reference
#include <U_Helper.hpp>
Public Types
enum class _MESSAGE_TYPE { TYPE_ERROR , TYPE_SUCCESS }
typedef enum U_HELPER::_MESSAGE_TYPE MESSAGE_TYPE
Static Public Member Functions
static BOOLEAN EnableVirtualTerminal (_Out_ HANDLE *hCon, _Out_ DWORD *dwDefaultMode)
static VOID WelcomeMessage ()
Welcome banner message.
static VOID PrintUsage ()
Message showing the possible arguments that the program can handle.
static BOOLEAN GetCurrentFolder (_Inout_ PWSTR szFolder)
static BOOLEAN GetDllFullPath (_Out_ PWSTR szPath)
static BOOLEAN GetHandleFromFileName (_Out_ HANDLE *hFileToCheck, _In_ PCWSTR szFileName)
static VOID DisplayError (_In_ PCWSTR szFunction)
This routine will display an error message based off of the Win32 error code that is passed in.
static VOID PrintMessage (_In_ MESSAGE_TYPE msgType, _In_ _Printf_format_string_ LPCTSTR szFormat,...)
Print error message in the terminal.
static VOID DisplayMessage (_In_ MESSAGE_TYPE msgType, _In_ _Printf_format_string_ LPCTSTR szFormat,...)
Popup error message displaying the function that failed associated with the error code.
static ULONG CountWStringsInBuffer (_In_ PCWSTR szBuffer, _In_ const ULONG ulSize)
Returns the number of Unicode strings found in a buffer (raw data from REG_MULTI_SZ)
static HANDLE GetProcessHandleByName (_In_ PWSTR szProcessName)
Member Typedef Documentation
MESSAGE_TYPE
typedef enum U_HELPER::_MESSAGE_TYPE U_HELPER::MESSAGE_TYPE
Member Enumeration Documentation
_MESSAGE_TYPE
enum class U_HELPER::_MESSAGE_TYPE strong
Enumerator
TYPE_ERROR
TYPE_SUCCESS
Member Function Documentation
CountWStringsInBuffer()
ULONG U_HELPER::CountWStringsInBuffer (_In_ PCWSTR szBuffer, _In_ const ULONG ulSize) static
Returns the number of Unicode strings found in a buffer (raw data from REG_MULTI_SZ)
Parameters
[in] szBuffer - pointer to a buffer that contains raw data from a REG_MULTI_SZ
[in] ulSize - szBuffer size in bytes
Returns
None.
Referenced by U_CONFIGURATION::GetWhitelist().
DisplayError()
VOID U_HELPER::DisplayError (_In_ PCWSTR szFunction) static
This routine will display an error message based off of the Win32 error code that is passed in.
This allows the user to see an understandable error message instead of just the code.
Parameters
[in] szFunction - Name of function which failed.
Returns
None.
Referenced by U_COMMUNICATION::_PumpMessageInQueue(), _Success_(), _tmain(), U_CONTROLLER::LaunchService(), and U_COMMUNICATION::ListenerThread().
DisplayMessage()
VOID U_HELPER::DisplayMessage (_In_ MESSAGE_TYPE msgType, _In_ _Printf_format_string_ LPCTSTR szFormat, ...) static
Popup error message displaying the function that failed associated with the error code.
Parameters
[in] msgType - Type of the associated message (warning, error, etc.)
[in] szFormat - Formatted string litteral
Returns
None.
Referenced by DisplayError().
EnableVirtualTerminal()
static BOOLEAN U_HELPER::EnableVirtualTerminal (_Out_ HANDLE * hCon, _Out_ DWORD * dwDefaultMode) static
Referenced by _tmain().
GetCurrentFolder()
static BOOLEAN U_HELPER::GetCurrentFolder (_Inout_ PWSTR szFolder) static
Referenced by U_CONTROLLER::InstallService().
GetDllFullPath()
static BOOLEAN U_HELPER::GetDllFullPath (_Out_ PWSTR szPath) static
Referenced by U_CONFIGURATION::_CreateRegistryForLogs().
GetHandleFromFileName()
static BOOLEAN U_HELPER::GetHandleFromFileName (_Out_ HANDLE * hFileToCheck, _In_ PCWSTR szFileName) static
Referenced by U_COMMUNICATION::_WorkerThread().
GetProcessHandleByName()
static HANDLE U_HELPER::GetProcessHandleByName (_In_ PWSTR szProcessName) static
PrintMessage()
VOID U_HELPER::PrintMessage (_In_ MESSAGE_TYPE msgType, _In_ _Printf_format_string_ LPCTSTR szFormat, ...) static
Print error message in the terminal.
Parameters
[in] msgType - Type of the associated message (warning, error, etc.)
[in] szFormat - Formatted string litteral
Returns
None.
Referenced by DisplayError(), and DisplayMessage().
PrintUsage()
VOID U_HELPER::PrintUsage () static
Message showing the possible arguments that the program can handle.
Parameters
None.
Returns
None.
Referenced by _tmain().
WelcomeMessage()
VOID U_HELPER::WelcomeMessage () static
Welcome banner message.
Parameters
None.
Returns
None.
Referenced by _tmain().
The documentation for this class was generated from the following files:
C:/Users/Gshoo/Desktop/pi-defender-tmp/Sources/PI-Defender_UM/U_Helper.hpp
C:/Users/Gshoo/Desktop/pi-defender-tmp/Sources/PI-Defender_UM/U_Helper.cpp