PI-Defender: U_REGISTRY Class Reference
U_REGISTRY Class Reference
#include <U_Registry.hpp>
Static Public Member Functions
static LSTATUS CreateRegistryKey (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey)
Create the registry key "szSubKey" located in the HIVE "hKeyParent".
static LSTATUS WriteDwordInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ DWORD dwData)
Write DWORD in the registry key "szSubKey" located in the HIVE "hKeyParent".
static LSTATUS WriteStringInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ PWSTR szData)
Write STRING in the registry key "szSubKey" located in the HIVE "hKeyParent".
static LSTATUS WriteMultiStringInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ const BYTE *pData, _In_ DWORD dwDataSize)
Write MULTI_SZ STRING in the registry key "szSubKey" located in the HIVE "hKeyParent".
static LSTATUS ReadValue (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ ULONG ulValueType, _Out_ PVOID *pData)
Read the content (DWORD) of the registry key "szSubKey" located in the HIVE "hKeyParent".
Static Private Member Functions
static LSTATUS _WriteDataInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ ULONG ulValueType, _In_ const BYTE *pData, _In_ DWORD dwDataSize)
Write data in the registry key "szSubKey" located in the HIVE "hKeyParent".
Member Function Documentation
_WriteDataInRegistry()
LSTATUS U_REGISTRY::_WriteDataInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ ULONG ulValueType, _In_ const BYTE * pData, _In_ DWORD dwDataSize) static private
Write data in the registry key "szSubKey" located in the HIVE "hKeyParent".
Parameters
[in] hKeyParent - Hive(HKLM, HKCU, etc..)
[in] szSubKey - Key that has to be created
[in] szValueName - Name of the value
[in] ulValueType - Type of the data (ex: REG_DWORD)
[in] pData - Pointer to the data (value) to store in the Registry
[in] dwDataSize - Size of data in bytes
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by WriteDwordInRegistry(), WriteMultiStringInRegistry(), and WriteStringInRegistry().
CreateRegistryKey()
LSTATUS U_REGISTRY::CreateRegistryKey (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey) static
Create the registry key "szSubKey" located in the HIVE "hKeyParent".
Parameters
[in] hKeyParent - Hive (HKLM, HKCU, etc..)
[in] szSubKey - Key that has to be created
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by U_CONFIGURATION::_CreateRegistryForLogs(), U_CONTROLLER::InstallService(), U_CONFIGURATION::SetDriverConfiguration(), and U_CONFIGURATION::SetServiceConfiguration().
ReadValue()
LSTATUS U_REGISTRY::ReadValue (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ ULONG ulValueType, _Out_ PVOID * pData) static
Read the content (DWORD) of the registry key "szSubKey" located in the HIVE "hKeyParent".
The return pointer pData is allocated here and needs to be free after use by the caller.
Parameters
[in] hKeyParent - Hive(HKLM, HKCU, etc..).
[in] szSubKey - Key that has to be created.
[in] szValueName - Name of the value.
[in] ulValueType - Type of the data (ex: REG_DWORD)
[out] pData - Pointer to the data (value) extracted from the Registry.
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by U_CONFIGURATION::GetCacheSize(), U_CONFIGURATION::GetCommunicationPort(), U_CONFIGURATION::GetListenerThreads(), U_CONFIGURATION::GetMaxClients(), U_CONFIGURATION::GetMaxWorkerThreads(), and U_CONFIGURATION::GetMinWorkerThreads().
WriteDwordInRegistry()
LSTATUS U_REGISTRY::WriteDwordInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ DWORD dwData) static
Write DWORD in the registry key "szSubKey" located in the HIVE "hKeyParent".
Parameters
[in] hKeyParent - Hive(HKLM, HKCU, etc..)
[in] szSubKey - Key that has to be created
[in] szValueName - Name of the value
[in] dwData - Value (int, hex, ..)
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by U_CONFIGURATION::_CreateRegistryForLogs(), U_CONTROLLER::InstallService(), U_CONFIGURATION::SetDriverConfiguration(), and U_CONFIGURATION::SetServiceConfiguration().
WriteMultiStringInRegistry()
LSTATUS U_REGISTRY::WriteMultiStringInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ const BYTE * pData, _In_ DWORD dwDataSize) static
Write MULTI_SZ STRING in the registry key "szSubKey" located in the HIVE "hKeyParent".
Parameters
[in] hKeyParent - Hive(HKLM, HKCU, etc..)
[in] szSubKey - Key that has to be created
[in] szValueName - Name of the value
[in] pData - Value (str with TWO terminating null-bytes)
[in] dwDataSize - Size of data in bytes
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by U_CONFIGURATION::SetDriverConfiguration().
WriteStringInRegistry()
LSTATUS U_REGISTRY::WriteStringInRegistry (_In_ HKEY hKeyParent, _In_ PCWSTR szSubKey, _In_ PCWSTR szValueName, _In_ PWSTR szData) static
Write STRING in the registry key "szSubKey" located in the HIVE "hKeyParent".
Parameters
[in] hKeyParent - Hive(HKLM, HKCU, etc..)
[in] szSubKey - Key that has to be created
[in] szValueName - Name of the value
[in] szData - Value (str)
Returns
ERROR_SUCCESS - No error occurs. Other status - Error status.
Referenced by U_CONFIGURATION::_CreateRegistryForLogs(), U_CONTROLLER::InstallService(), and U_CONFIGURATION::SetDriverConfiguration().
The documentation for this class was generated from the following files:
C:/Users/Gshoo/Desktop/pi-defender-tmp/Sources/PI-Defender_UM/U_Registry.hpp
C:/Users/Gshoo/Desktop/pi-defender-tmp/Sources/PI-Defender_UM/U_Registry.cpp