PI-Defender: K_CONFIGURATION Class Reference
K_CONFIGURATION Class Reference
#include <K_Configuration.hpp>
Public Member Functions
VOID Unload ()
Free previously allocated memory.
NTSTATUS Initialize (_In_ PUNICODE_STRING szRegistryPath)
Initialize configuration from Registry.
PCWSTR GetCommunicationPort ()
ULONG GetMaxClients ()
Static Public Member Functions
static NTSTATUS IsInWhitelist (_In_ PUNICODE_STRING szTestString, _Out_ BOOLEAN *bResult)
static BOOLEAN IsInCache (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN *bResult)
static VOID AddToCache (_In_ ULONG cbHash, _In_ PVOID pHash, _In_ BOOLEAN bIsSigned)
Private Attributes
PCWSTR _szCommunicationPort
ULONG _ulMaxClients
Member Function Documentation
AddToCache()
static VOID K_CONFIGURATION::AddToCache (_In_ ULONG cbHash, _In_ PVOID pHash, _In_ BOOLEAN bIsSigned) inline static
Referenced by K_OB::_PreObCallback().
GetCommunicationPort()
PCWSTR K_CONFIGURATION::GetCommunicationPort () inline
Referenced by K_FILTER::Initialize().
GetMaxClients()
ULONG K_CONFIGURATION::GetMaxClients () inline
Referenced by K_FILTER::Initialize().
Initialize()
NTSTATUS K_CONFIGURATION::Initialize (_In_ PUNICODE_STRING szRegistryPath)
Initialize configuration from Registry.
Must be called once before calling others methods of this class.
The configuration is loaded from HKLM\SYSTEM\CurrentControlSet\Services\PI-Defender\Parameters.
Parameters
[in] szRegistryPath - Registry path to service key
Returns
STATUS_SUCCESS - No error occurs.
Other status - Error status. For more information, see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
Referenced by DriverEntry().
IsInCache()
static BOOLEAN K_CONFIGURATION::IsInCache (_In_ ULONG ulHashSize, _In_ PVOID pHash, _Out_opt_ BOOLEAN * bResult) inline static
Referenced by K_OB::_PreObCallback().
IsInWhitelist()
static NTSTATUS K_CONFIGURATION::IsInWhitelist (_In_ PUNICODE_STRING szTestString, _Out_ BOOLEAN * bResult) inline static
Referenced by K_OB::_PreObCallback().
Unload()
VOID K_CONFIGURATION::Unload ()
Free previously allocated memory.
Called by DriverUnload.
Parameters
None.
Returns
None.
Referenced by DriverUnload().
Member Data Documentation
_szCommunicationPort
PCWSTR K_CONFIGURATION::_szCommunicationPort private
Referenced by GetCommunicationPort(), Initialize(), and Unload().
_ulMaxClients
ULONG K_CONFIGURATION::_ulMaxClients private
Referenced by GetMaxClients(), and Initialize().
The documentation for this class was generated from the following files:
K_Configuration.hpp
K_Configuration.cpp